Added cancer hallmark full publications details (rows)
opentargets-archive/platform-api-experimental pull request #19
Opened 2019-05-14 18:58 UTC by LucaFumis

Added plain `rows` to cancerHallmarks query.

2019-05-15 11:15 UTC, peatroot commented on src/apis/dataloaders.js
> +                activity: d.promote ? 'promotes' : (d.suppress ? 'suppresses' : ''),
Maybe `activity` is redundant? It seems to be derived from `promotes` and `suppresses`.

2019-05-15 11:16 UTC, peatroot commented on src/schema/details/CancerHallmarks.js
> +    rows: [CancerHallmarkPublicationFullDetails!]
Probably want `rows: [CancerHallmarkPublicationFullDetails!]!`.

2019-05-15 11:17 UTC, peatroot requested changes
Looks good. Minor tweaks suggested.

2019-05-16 10:16 UTC, LucaFumis commented on src/apis/dataloaders.js
> +                activity: d.promote ? 'promotes' : (d.suppress ? 'suppresses' : ''),
Addressed in last commit https://github.com/opentargets/platform-api/pull/19/commits/6152f197ae651b794e008781b4d93d22f194a849

2019-05-16 10:16 UTC, LucaFumis commented on src/schema/details/CancerHallmarks.js
> +    rows: [CancerHallmarkPublicationFullDetails!]
https://github.com/opentargets/platform-api/pull/19/commits/6152f197ae651b794e008781b4d93d22f194a849

2019-05-16 12:39 UTC, merged